FROM nvidia/cuda:11.8.0-base-ubuntu22.04

ENV IMAGE_NAME DNN11

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    ca-certificates \
    python3-dev \ 
    p7zip-full \ 
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y --no-install-recommends wget

ENV PYTHONPATH "${PYTHONPATH}/app"

WORKDIR /app

COPY requirements.txt .

RUN pip --no-cache-dir install -r requirements.txt

RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

RUN pip install --upgrade ipykernel

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
