FROM python:3.10-slim-buster as builder

WORKDIR /app

RUN apt-get update && \
    apt-get install --no-install-recommends -y build-essential

COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

FROM python:3.10-slim-buster

ENV PYTHONPATH "${PYTHONPATH}/app"

WORKDIR /app

COPY --from=builder /install /usr/local

COPY .env .
COPY main.py .
COPY src ./src

ENTRYPOINT ["streamlit", "run", "--server.address", "0.0.0.0", "main.py"]